#!/bin/bash
#PBS -q normal
#PBS -lstorage=scratch/ab01+data/ab01
#PBS -l walltime=20:00:00
#PBS -l mem=64GB
#PBS -l jobfs=100GB
#PBS -l ncpus=12
#PBS -l wd
#PBS -j oe
#PBS -m abe
#PBS -M username@email.com
#PBS -N discoAnt

source activate discoAnt.env

module load foss/2019b
module load r/4.0.5
module load gcc/10.2.0
module load samtools/1.12
module load gffread/0.12.7
module load gffcompare/0.12.2 
module load minimap2
module load salmon

bash /path/to/folder/discoAnt/discoAnt.sh
