#!/bin/bash

#conda env create -f discoAnt.yml 
source env create -f discoAnt.yml

#conda activate discoAnt
source activate discoAnt

# install SQANTI
cd scripts
git clone https://github.com/ConesaLab/SQANTI3.git
chmod +x scripts/SQANTI3/utilities/gtfToGenePred

# install cDNA Cupcake
git clone https://github.com/youyupei/cDNA_Cupcake.git
cd cDNA_Cupcake
python setup.py build
python setup.py install

conda deactivate 

